name: Generate Snake Animation

# Exécuter à minuit tous les jours
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérification du dépôt (checkout)
      - name: Checkout
        uses: actions/checkout@v3

      # Générer les fichiers SVG et GIF du snake
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Utilise le nom de l'utilisateur GitHub
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Pousser le SVG généré dans la branche "output"
      - name: Push Generated Snake to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
